// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:7cec72ef-0f06-4293-9aea-5dd34f26b890",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_SNevDEyxS",
    "aws_user_pools_web_client_id": "410rt8eedb6pcd95kf02fbtnt8",
    "aws_appsync_graphqlEndpoint": "https://77ibsouvozghpkziy5huirug2i.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-pqthy66anjb47meia4zfv72a2y"
};


export default awsmobile;
